name: Android Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'oracle'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/uniconv.apk
    - name: Upload built APK
      uses: actions/upload-artifact@v3.1.2
      with:
        name: Uniconv APK
        path: app/build/outputs/apk/release/uniconv.apk
